linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - goconst
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/cafedomingo/SKU_RM0004
