version: "2"

linters:
  enable:
    - errcheck
    - goconst
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/cafedomingo/SKU_RM0004
