// bdf2go downloads Spleen BDF font data and generates a Go source file
// containing bitmap glyph data for use in the font package.
package main

import (
	"archive/tar"
	"bufio"
	"compress/gzip"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

const defaultSpleenVersion = "2.1.0"

// wantedRunes8x16 is the set of Unicode code points to extract from the 8x16 BDF file.
var wantedRunes8x16 = func() map[rune]bool {
	m := make(map[rune]bool)
	// ASCII printable range
	for r := rune(32); r <= 126; r++ {
		m[r] = true
	}
	// Degree sign
	m[0x00B0] = true
	// Geometric shapes
	m[0x25B2] = true // ▲
	m[0x25BC] = true // ▼
	m[0x25C6] = true // ◆
	// Block elements ▁▂▃▄▅▆▇█
	for r := rune(0x2581); r <= 0x2588; r++ {
		m[r] = true
	}
	return m
}()

// wantedRunes6x12 is the set of Unicode code points to extract from the 6x12 BDF file.
// Spleen 6x12 covers ASCII and Latin-1 Supplement. We only need ASCII for our purposes.
var wantedRunes6x12 = func() map[rune]bool {
	m := make(map[rune]bool)
	// ASCII printable range
	for r := rune(32); r <= 126; r++ {
		m[r] = true
	}
	return m
}()

// BDFGlyph holds parsed data for a single BDF character.
type BDFGlyph struct {
	Encoding rune
	Bitmap   []byte
}

// ParseBDF extracts glyphs from BDF-formatted data, returning only those
// whose encoding appears in the wanted set.
func ParseBDF(r io.Reader, wanted map[rune]bool) ([]BDFGlyph, error) {
	var glyphs []BDFGlyph
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		line := scanner.Text()
		if !strings.HasPrefix(line, "STARTCHAR ") {
			continue
		}

		var encoding int
		inBitmap := false
		var bitmap []byte

		for scanner.Scan() {
			line = scanner.Text()

			if strings.HasPrefix(line, "ENCODING ") {
				val := strings.TrimPrefix(line, "ENCODING ")
				n, err := strconv.Atoi(strings.TrimSpace(val))
				if err != nil {
					return nil, fmt.Errorf("bad ENCODING: %q", val)
				}
				encoding = n
			} else if line == "BITMAP" {
				inBitmap = true
			} else if line == "ENDCHAR" {
				if wanted[rune(encoding)] {
					glyphs = append(glyphs, BDFGlyph{
						Encoding: rune(encoding),
						Bitmap:   bitmap,
					})
				}
				break
			} else if inBitmap {
				b, err := strconv.ParseUint(strings.TrimSpace(line), 16, 8)
				if err != nil {
					return nil, fmt.Errorf("bad bitmap hex %q: %w", line, err)
				}
				bitmap = append(bitmap, byte(b))
			}
		}
	}

	return glyphs, scanner.Err()
}

// bdfSpec describes a BDF file to extract from the tarball.
type bdfSpec struct {
	filename string
	wanted   map[rune]bool
}

func downloadAndExtractBDFs(version string, specs []bdfSpec) (map[string][]byte, error) {
	url := fmt.Sprintf("https://github.com/fcambus/spleen/releases/download/%s/spleen-%s.tar.gz", version, version)
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("download: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("download: HTTP %d", resp.StatusCode)
	}

	gz, err := gzip.NewReader(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("gzip: %w", err)
	}
	defer gz.Close()

	// Build target set
	targets := make(map[string]string) // tarball path -> spec filename
	for _, s := range specs {
		target := fmt.Sprintf("spleen-%s/%s", version, s.filename)
		targets[target] = s.filename
	}

	results := make(map[string][]byte)
	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("tar: %w", err)
		}
		if _, ok := targets[hdr.Name]; ok {
			data, err := io.ReadAll(tr)
			if err != nil {
				return nil, fmt.Errorf("read %s: %w", hdr.Name, err)
			}
			results[targets[hdr.Name]] = data
			if len(results) == len(targets) {
				break
			}
		}
	}

	for _, s := range specs {
		if _, ok := results[s.filename]; !ok {
			return nil, fmt.Errorf("%s not found in tarball", s.filename)
		}
	}

	return results, nil
}

func runeLabel(r rune) string {
	if r == '\'' {
		return `'\''`
	}
	if r == '\\' {
		return `'\\'`
	}
	if r >= 32 && r <= 126 {
		return fmt.Sprintf("'%c'", r)
	}
	return fmt.Sprintf("'\\u%04X'", r)
}

type fontDef struct {
	varName string
	width   int
	height  int
	glyphs  []BDFGlyph
}

func generateGo(fonts []fontDef, version string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by bdf2go from Spleen (v%s). DO NOT EDIT.\n", version)
	b.WriteString("// Spleen is Copyright (c) 2018-2024 Frederic Cambus, BSD 2-Clause License.\n")
	b.WriteString("// See THIRD_PARTY_LICENSES for details.\n\n")
	b.WriteString("package font\n")

	for _, fd := range fonts {
		sort.Slice(fd.glyphs, func(i, j int) bool {
			return fd.glyphs[i].Encoding < fd.glyphs[j].Encoding
		})

		fmt.Fprintf(&b, "\nvar %s = &Font{\n", fd.varName)
		fmt.Fprintf(&b, "\tWidth:  %d,\n", fd.width)
		fmt.Fprintf(&b, "\tHeight: %d,\n", fd.height)
		b.WriteString("\tGlyphs: map[rune][]byte{\n")

		for _, g := range fd.glyphs {
			label := runeLabel(g.Encoding)
			hexes := make([]string, len(g.Bitmap))
			for i, v := range g.Bitmap {
				hexes[i] = fmt.Sprintf("0x%02x", v)
			}
			fmt.Fprintf(&b, "\t\t%s: {%s},\n", label, strings.Join(hexes, ", "))
		}

		b.WriteString("\t},\n")
		b.WriteString("}\n")
	}

	return b.String()
}

func main() {
	version := flag.String("version", defaultSpleenVersion, "Spleen release version")
	flag.Parse()

	specs := []bdfSpec{
		{filename: "spleen-6x12.bdf", wanted: wantedRunes6x12},
		{filename: "spleen-8x16.bdf", wanted: wantedRunes8x16},
	}

	log.Printf("Downloading Spleen %s...", *version)
	bdfData, err := downloadAndExtractBDFs(*version, specs)
	if err != nil {
		log.Fatal(err)
	}

	var fonts []fontDef
	for _, spec := range specs {
		data := bdfData[spec.filename]
		log.Printf("Parsing %s (%d bytes)...", spec.filename, len(data))
		glyphs, err := ParseBDF(strings.NewReader(string(data)), spec.wanted)
		if err != nil {
			log.Fatalf("parsing %s: %v", spec.filename, err)
		}
		log.Printf("Extracted %d glyphs from %s", len(glyphs), spec.filename)

		switch spec.filename {
		case "spleen-6x12.bdf":
			fonts = append(fonts, fontDef{varName: "Spleen6x12", width: 6, height: 12, glyphs: glyphs})
		case "spleen-8x16.bdf":
			fonts = append(fonts, fontDef{varName: "Spleen8x16", width: 8, height: 16, glyphs: glyphs})
		}
	}

	src := generateGo(fonts, *version)

	// Determine output path relative to this tool's source location.
	_, thisFile, _, _ := runtime.Caller(0)
	outPath := filepath.Join(filepath.Dir(thisFile), "..", "..", "internal", "font", "spleen.go")
	outPath = filepath.Clean(outPath)

	if err := os.WriteFile(outPath, []byte(src), 0644); err != nil {
		log.Fatal(err)
	}
	log.Printf("Wrote %s (%d bytes)", outPath, len(src))
}
