// bdf2go downloads Spleen BDF font data and generates a Go source file
// containing bitmap glyph data for use in the font package.
package main

import (
	"archive/tar"
	"bufio"
	"compress/gzip"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

const defaultSpleenVersion = "2.1.0"

// wantedRunes is the set of Unicode code points to extract from the BDF file.
var wantedRunes = func() map[rune]bool {
	m := make(map[rune]bool)
	// ASCII printable range
	for r := rune(32); r <= 126; r++ {
		m[r] = true
	}
	// Degree sign
	m[0x00B0] = true
	// Geometric shapes
	m[0x25B2] = true // ▲
	m[0x25BC] = true // ▼
	m[0x25C6] = true // ◆
	// Block elements ▁▂▃▄▅▆▇█
	for r := rune(0x2581); r <= 0x2588; r++ {
		m[r] = true
	}
	return m
}()

// BDFGlyph holds parsed data for a single BDF character.
type BDFGlyph struct {
	Encoding rune
	Bitmap   []byte
}

// ParseBDF extracts glyphs from BDF-formatted data, returning only those
// whose encoding appears in the wanted set.
func ParseBDF(r io.Reader, wanted map[rune]bool) ([]BDFGlyph, error) {
	var glyphs []BDFGlyph
	scanner := bufio.NewScanner(r)

	for scanner.Scan() {
		line := scanner.Text()
		if !strings.HasPrefix(line, "STARTCHAR ") {
			continue
		}

		var encoding int
		inBitmap := false
		var bitmap []byte

		for scanner.Scan() {
			line = scanner.Text()

			if strings.HasPrefix(line, "ENCODING ") {
				val := strings.TrimPrefix(line, "ENCODING ")
				n, err := strconv.Atoi(strings.TrimSpace(val))
				if err != nil {
					return nil, fmt.Errorf("bad ENCODING: %q", val)
				}
				encoding = n
			} else if line == "BITMAP" {
				inBitmap = true
			} else if line == "ENDCHAR" {
				if wanted[rune(encoding)] {
					glyphs = append(glyphs, BDFGlyph{
						Encoding: rune(encoding),
						Bitmap:   bitmap,
					})
				}
				break
			} else if inBitmap {
				b, err := strconv.ParseUint(strings.TrimSpace(line), 16, 8)
				if err != nil {
					return nil, fmt.Errorf("bad bitmap hex %q: %w", line, err)
				}
				bitmap = append(bitmap, byte(b))
			}
		}
	}

	return glyphs, scanner.Err()
}

func downloadAndExtractBDF(version string) ([]byte, error) {
	url := fmt.Sprintf("https://github.com/fcambus/spleen/releases/download/%s/spleen-%s.tar.gz", version, version)
	resp, err := http.Get(url)
	if err != nil {
		return nil, fmt.Errorf("download: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("download: HTTP %d", resp.StatusCode)
	}

	gz, err := gzip.NewReader(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("gzip: %w", err)
	}
	defer gz.Close()

	target := fmt.Sprintf("spleen-%s/spleen-8x16.bdf", version)
	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if err == io.EOF {
			return nil, fmt.Errorf("spleen-8x16.bdf not found in tarball")
		}
		if err != nil {
			return nil, fmt.Errorf("tar: %w", err)
		}
		if hdr.Name == target {
			return io.ReadAll(tr)
		}
	}
}

func runeLabel(r rune) string {
	if r == '\'' {
		return `'\''`
	}
	if r == '\\' {
		return `'\\'`
	}
	if r >= 32 && r <= 126 {
		return fmt.Sprintf("'%c'", r)
	}
	return fmt.Sprintf("'\\u%04X'", r)
}

func generateGo(glyphs []BDFGlyph, version string) string {
	sort.Slice(glyphs, func(i, j int) bool {
		return glyphs[i].Encoding < glyphs[j].Encoding
	})

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by bdf2go from Spleen 8x16 (v%s). DO NOT EDIT.\n", version)
	b.WriteString("// Spleen is Copyright (c) 2018-2024 Frederic Cambus, BSD 2-Clause License.\n")
	b.WriteString("// See THIRD_PARTY_LICENSES for details.\n\n")
	b.WriteString("package font\n\n")
	b.WriteString("var Spleen8x16 = &Font{\n")
	b.WriteString("\tWidth:  8,\n")
	b.WriteString("\tHeight: 16,\n")
	b.WriteString("\tGlyphs: map[rune][]byte{\n")

	for _, g := range glyphs {
		label := runeLabel(g.Encoding)
		hexes := make([]string, len(g.Bitmap))
		for i, v := range g.Bitmap {
			hexes[i] = fmt.Sprintf("0x%02x", v)
		}
		fmt.Fprintf(&b, "\t\t%s: {%s},\n", label, strings.Join(hexes, ", "))
	}

	b.WriteString("\t},\n")
	b.WriteString("}\n")
	return b.String()
}

func main() {
	version := flag.String("version", defaultSpleenVersion, "Spleen release version")
	flag.Parse()

	log.Printf("Downloading Spleen %s...", *version)
	bdfData, err := downloadAndExtractBDF(*version)
	if err != nil {
		log.Fatal(err)
	}

	log.Printf("Parsing BDF (%d bytes)...", len(bdfData))
	glyphs, err := ParseBDF(strings.NewReader(string(bdfData)), wantedRunes)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Extracted %d glyphs", len(glyphs))

	src := generateGo(glyphs, *version)

	// Determine output path relative to this tool's source location.
	_, thisFile, _, _ := runtime.Caller(0)
	outPath := filepath.Join(filepath.Dir(thisFile), "..", "..", "internal", "font", "spleen.go")
	outPath = filepath.Clean(outPath)

	if err := os.WriteFile(outPath, []byte(src), 0644); err != nil {
		log.Fatal(err)
	}
	log.Printf("Wrote %s (%d bytes)", outPath, len(src))
}
